### ISSUE TITLE
querySelector css selector constructor

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [purescript-web/purescript-web-dom#18]
It would be really awesome to use the [CSS.Selector.Predicate](https://pursuit.purescript.org/packages/purescript-css/4.0.0/docs/CSS.Selector#t:Predicate) instead of the [QuerySelector](https://pursuit.purescript.org/packages/purescript-web-dom/4.0.0/docs/Web.DOM.ParentNode#t:QuerySelector) because it has better composition.

**Comment by garyb** [comment]
That's probably not going to happen since the CSS library is opinionated, and the goal of the `purescript-web` projects is to provide an as-unopinionated-as-is-reasonable, low level interface to the browser APIs.

I'd say the current situation has better compositional properties, because you can either use CSS or not, and to make it work you just insert a call to render the CSS when setting relevant properties :wink:

**Comment by BebeSparkelSparkel** [comment]
Understandable, thanks.
